spring:
  application:
    name: configserver
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:///C:\Users\mstra\Desktop\projects\config-mgmt\configserver\src\main\resources\config
#          search-location: classpath:/config
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: "busrefresh"

#  datasource:
#    url: jdbc:mysql://localhost:3306/configdb
#    username: root
#    password: ihvadream
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  cloud:
#    config:
#      server:
#        jdbc:
#          sql: "SELECT PROP_KEY, PROP_VALUE FROM PROPERTIES WHERE APPLICATION=? AND PROFILE=? AND LABEL=?"
#          default-label: main

#  cloud:
#    config:
#      server:
#        git:
#          uri: https://github.com/amosuzuagie/app-configuration
#          username: ${GIT_USERNAME}
#          password: ${GIT_PASSWORD}
server:
  port: 8888

#encrypt:
#  key: "0ANDBYPASSWELDJ73DLALF30LSQ"

encrypt:
  key-store:
    location: config-server.jks
    password: mypass
    alias: config-server-key