spring:
  application:
    name: configdemo
  profiles:
    active: dev
  config:
    import: optional:configserver:http://localhost:8888
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest


build:
  id: ${ID}
  version: ${VERSION}
  name: ${NAME}
  type: ${TYPE}


management:
  endpoints:
    web:
      exposure:
        include: "*"

