build:
  id: 111
  version: 1.0
  name: "Native Dev-Build Little Update"
  type: "Native Development Build updated"


spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: "busrefresh"